services:
  backend:
    build: ./backend
    container_name: backend_nutricion
    env_file:
      - .env
    environment:
      ANEMIA_ASYNC: "true"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/models:/app/models
      - ./backend/uploads:/tmp/uploads
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
  redis:
    image: redis:7
    container_name: redis_anemia
    ports:
      - "6379:6379"

  celery_worker:
    build: ./backend
    container_name: celery_anemia_worker
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend:/app
      - ./backend/uploads:/tmp/uploads
    environment:
      REDIS_URL: "redis://redis:6379/0"
      ANEMIA_ASYNC: "true"
    command: celery -A tasks.celery_app worker --loglevel=info


